#!/usr/bin/env bash
# Installs and configure HAproxy on my lb-01 server.

# Install HAproxy
sudo apt update
sudo apt-get install -y haproxy

# Let HAProxy be able to be managed using init script
sudo  echo "ENABLED=1" | sudo tee -a "/etc/default/haproxy"
sudo printf "\nlisten www\n\tbind :80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?status\n\tbalance roundrobin\n\tserver 51149-web-01 54.237.81.19:80 check\n\tserver 51149-web-02 34.204.60.234:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
sudo service haproxy restart
