#!/usr/bin/env bash
# script to discover if hosts are on the network using ping.
# Script to ping 5 times

if [ "$1" ]; then
    ping -c 5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi