#!/usr/bin/env bash
# Configures nginx to listen on port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
