#!/user/bin/env bash

sudo apt update
sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/ssh
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
